name: Build Website Image
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: "Environment (dev, staging, prod)"

env:
  IMAGE: isagog-website:${{ inputs.env }}-${{ github.sha }}

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ inputs.env }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --target runner \
            -t $IMAGE \
            .

      - name: Save image details
        run: echo "WEBSITE_IMAGE=$IMAGE" > image.env

      - name: Upload image details
        uses: actions/upload-artifact@v4
        with:
          name: image-details
          path: image.env
          retention-days: 1
